ALTER TABLE [dbo].[Ugyfel]
ALTER COLUMN [NEV] ADD MASKED WITH (FUNCTION = 'default()');

ALTER TABLE [dbo].[Ugyfel]
ALTER COLUMN [SZULEV] ADD MASKED WITH (FUNCTION = 'random(1,99)');

ALTER TABLE [dbo].[Ugyfel]
ALTER COLUMN [CIM] ADD MASKED WITH (FUNCTION = 'partial(3,"XXXXXX",1)');

ALTER TABLE [dbo].[Ugyfel]
ALTER COLUMN [EMAIL] ADD MASKED WITH (FUNCTION = 'email()');